[server]
port = 3001
debug = true
[server.tls]
enabled = false
cert_file = "./certs/server.crt"
key_file = "./certs/server.key"

[database]
uri = "mongodb://100.93.246.119:27017"
database = "nishiki"
timeout = 10

[auth]
authentik_url = "https://192.168.0.125:30141"
provider_name = "nishiki"
client_id = "VVyph7MnbGDqtiPq8vfgl51ECIO2GcgZ12skA4VR"
client_secret = "oN5PbDi7lvZLUFowbuCOF8ZHRy0z9futAaPqnrAylhcApOhGLeVFa0hrVPv8OI7ovlzUL0XLAYBbbmsYSPzFBfPXtQbAkrsY3aacaFyEjuSWkucdP8YPkTUCAw7C7v9m"
redirect_url = "http://localhost:3001/auth/callback"
jwks_cache_duration = 300
allow_self_signed = true
api_token = "CU1uS8cQIC9HYiqkW20eQFMgI6ibx6lPTskyZ4lLYxOBaXg0DfBalLC0g5ZY"

[logging]
level = "debug"
seq_endpoint = "http://100.93.246.119:5380"
seq_api_key = "7mpeTBjnxYEqcftSLG5c"
