// Code generated by MockGen. DO NOT EDIT.
// Source: collection_repository.go
//
// Generated by this command:
//
//	mockgen -source=collection_repository.go -destination=../../mocks/mock_collection_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/nishiki/backend-go/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionRepository is a mock of CollectionRepository interface.
type MockCollectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionRepositoryMockRecorder
	isgomock struct{}
}

// MockCollectionRepositoryMockRecorder is the mock recorder for MockCollectionRepository.
type MockCollectionRepositoryMockRecorder struct {
	mock *MockCollectionRepository
}

// NewMockCollectionRepository creates a new mock instance.
func NewMockCollectionRepository(ctrl *gomock.Controller) *MockCollectionRepository {
	mock := &MockCollectionRepository{ctrl: ctrl}
	mock.recorder = &MockCollectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionRepository) EXPECT() *MockCollectionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCollectionRepository) Create(ctx context.Context, collection *entities.Collection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, collection)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCollectionRepositoryMockRecorder) Create(ctx, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCollectionRepository)(nil).Create), ctx, collection)
}

// Delete mocks base method.
func (m *MockCollectionRepository) Delete(ctx context.Context, id entities.CollectionID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCollectionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCollectionRepository)(nil).Delete), ctx, id)
}

// Exists mocks base method.
func (m *MockCollectionRepository) Exists(ctx context.Context, id entities.CollectionID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCollectionRepositoryMockRecorder) Exists(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCollectionRepository)(nil).Exists), ctx, id)
}

// GetByGroupID mocks base method.
func (m *MockCollectionRepository) GetByGroupID(ctx context.Context, groupID entities.GroupID) ([]*entities.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGroupID", ctx, groupID)
	ret0, _ := ret[0].([]*entities.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGroupID indicates an expected call of GetByGroupID.
func (mr *MockCollectionRepositoryMockRecorder) GetByGroupID(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGroupID", reflect.TypeOf((*MockCollectionRepository)(nil).GetByGroupID), ctx, groupID)
}

// GetByID mocks base method.
func (m *MockCollectionRepository) GetByID(ctx context.Context, id entities.CollectionID) (*entities.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCollectionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCollectionRepository)(nil).GetByID), ctx, id)
}

// GetByUserID mocks base method.
func (m *MockCollectionRepository) GetByUserID(ctx context.Context, userID entities.UserID) ([]*entities.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entities.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockCollectionRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockCollectionRepository)(nil).GetByUserID), ctx, userID)
}

// List mocks base method.
func (m *MockCollectionRepository) List(ctx context.Context, limit, offset int) ([]*entities.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]*entities.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCollectionRepositoryMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCollectionRepository)(nil).List), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockCollectionRepository) Update(ctx context.Context, collection *entities.Collection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, collection)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCollectionRepositoryMockRecorder) Update(ctx, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCollectionRepository)(nil).Update), ctx, collection)
}
